apiVersion: v1
kind: Service
metadata:
  name: subscription-svc
  labels:
    app: subscription
    env: dev
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9000
  selector:
    app: subscription
  type: ClusterIP