apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: subscription
    env: dev
  name: subscription-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: subscription-backend
  template:
    metadata:
      labels:
        app: subscription
        env: dev
        name: subscription-backend
    spec:
      containers:
        - name: subscription
          image: thiago123789/subscription:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: spring.rabbitmq.addresses
              valueFrom:
                secretKeyRef:
                  key: rabbit.url
                  name: subscription-secrets
            - name: database.user
              valueFrom:
                secretKeyRef:
                  key: mysql.user
                  name: subscription-secrets
            - name: database.pass
              valueFrom:
                secretKeyRef:
                  key: mysql.pass
                  name: subscription-secrets
            - name: database.url
              value: jdbc:mysql://mysql-subscription-svc:3306/subscriptions?createDatabaseIfNotExist=true
      volumes:
        - name: secret-volum
          secret:
            secretName: subscription-secrets
