apiVersion: v1
kind: Service
metadata:
  name: email-svc
  labels:
    app: email
    env: dev
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8095
  selector:
    app: email
  type: ClusterIP