apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit
  namespace: adidas
  labels:
    app: subcription
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: subscription
  serviceName: rabbit
  template:
    metadata:
      labels:
        app: subscription
    spec:
      nodeSelector:
        kubenertes.io/os: linux
      containers:
        - name: rabbit
          image: rabbit:3.9
          volumeMounts:
            - mountPath: config-volume
              name: /etc/rabbitmq
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: amqp
              protocol: TCP
              containerPort: 5672
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "status"]
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
          imagePullPolicy: Always
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
            - name: K8S_SERVICE_NAME
              value: rabbit
            - name: RABBITMQ_NODENAME
              value: rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAME).svc.cluster.local
            - name:
              value:
