apiVersion: v1
kind: Secret
metadata:
  name: subscription-secrets
data:
  rabbit.url: YW1xcHM6Ly9ncm1oaHhzejowWF9SamVOcFVsSGZZUlVfT3VmZWpfZXYyb1VmMnBLNEBjaGltcGFuemVlLnJtcS5jbG91ZGFtcXAuY29tL2dybWhoeHN6
  mysql.user: cm9vdA==
  mysql.pass: cm9vdA==